django_recsys/urls.py
from django.contrib import admin
from django.urls import path, include
from recapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #관리자 기능을 사용하기 위한 url
    path('', views.index, name='index'),
    #홈으로 이동하기 위한 url
    #현재 사이트의 홈은 recapp의 place_list로 연결되게 설정되어 있으므로, recapp.view의 index가 실행되게 설정
    path('recapp/', include('recapp.urls')),
    #recapp 기능을 사용하기 위한 url => include로 recapp 내부에서 관리
    path('signapp/', include('signapp.urls')),
    #signapp 기능을 사용하기 위한 url => include로 signapp 내부에서 관리
]

recapp/urls.py
from django.urls import path
from . import views

app_name = 'recapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:place_id>/', views.place_detail, name='detail'),
    path('review/create/<int:place_id>/', views.review_create, name='review_create'),
    path('review/create/<int:review_id>', views.review_modify, name='review_modify'),
    path('review/delete/<int:review_id>', views.review_delete, name='review_delete'),
]

recapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg

# Create your models here.

class Place(models.Model):
    place_name = models.CharField(max_length=50)
    place_location = models.CharField(max_length=100)
    place_tags = models.TextField()

    def __str__(self):
        return self.place_name

    @property
    def average_rating(self):
        return round(self.review_set.aggregate(Avg('rating'))['rating__avg'], 1)

    class Meta:
        db_table = 'places'

class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    content = models.TextField()
    rating = models.IntegerField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)
    #null, blank 조건을 통해 null값 또는 아예 폼에서 입력을 안하는 것을 허용


    class Meta:
        db_table = 'reviews'

recapp/forms.py
from django import forms
from recapp.models import Place, Review

#리뷰생성을 위한 폼
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'content']
        #create_time은 자동 생성
        labels = {
            'rating': '평점',
            'content': '한줄평',

        }

recapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Place, Review
from django.utils import timezone
from .forms import ReviewForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django_recsys.settings import get_secret
import requests
import logging

logger = logging.getLogger(__name__)

RECSYS_RESTAPI = get_secret("RECSYS_RESTAPI")

# Create your views here.
def index(request):


    #홈화면에 바로 맛집 목록을 띄워 준다.
    page = request.GET.get('page', '1')
    #디폴트 페이지는 첫번째 페이지로 지정
    place_list = Place.objects.order_by('id')
    #이름 순으로 정렬

    paginator = Paginator(place_list, 20)
    page_obj = paginator.get_page(page)

    recommends = list()
    if request.user.is_authenticated:
        target = request.user
        # 개인화 추천 (CF) 요청 => 추천 API 서버 => 추천 결과 => res
        res = ((requests.post(RECSYS_RESTAPI + '/recommender/cfrecommend',
                              data={"sofo_name": target.profile.sofo_name}))).json()
        if res != 'No Review':
            for i in range(len(res)):
                temp = get_object_or_404(Place, pk=res[i])
                recommends.append(temp)

    context = {'place_list' : page_obj, 'recommends' : recommends}
    #place_list를 20개씩 쪼깬 page 객체를 render 함수에 변수(place_list)로 넘겨줌
    return render(request, 'recapp/place_list.html', context)

def place_detail(request, place_id):
    place = get_object_or_404(Place ,pk=place_id)
    # 사용자 행동(맛집 조회) 로그 수집
    if request.user.is_authenticated:
        logger.info('{} {} [{}]'.format(request.user.username, 'BROWSE' ,place.place_name))
    # 유사한 맛집 (CB) 추천 요청 => 추천 API 서버 => 추천 결과 => res
    res = ((requests.get(RECSYS_RESTAPI + '/recommender/cbrecommend/' + str(place_id)))).json()
    similars = list()
    for i in range(len(res)):
        temp = get_object_or_404(Place, pk=res[i])
        similars.append(temp)
    context = {'place' : place, 'similars' : similars}
    return render(request, 'recapp/place_detail.html', context)

#리뷰는 로그인이 필요하므로 로그아웃 상태에서 리뷰생성을 호출하면 바로 로그인 화면으로 이동되게
#login_required를 붙여줌
@login_required(login_url='signapp:signin')
def review_create(request, place_id):

    place = get_object_or_404(Place, pk=place_id)

    if request.method == "POST":
        form = ReviewForm(request.POST)
        #리뷰 등록 시도(POST), 사용자가 폼 형식으로 작성한 폼 객체를 받는다.
        if form.is_valid():
            review = form.save(commit=False)
            #폼과 연결된 review 모델을 저장하지는 않고, 객체만 반환 (아직 설정되지 않은 객체 필드 값 author, place들이 존재함)
            review.author = request.user
            #현재 로그인한, 즉 현재 요청을 보내는 user 객체를 author로 설정
            review.place = place
            #review의 foreign key인 place와 관계 형성
            review.save()
            #폼 형식으로 리뷰 등록하고 redirect로 return

            # training 데이터로 수집
            requests.post(RECSYS_RESTAPI + '/etl/reviewetl',
                          data={"user_name": review.author.profile.sofo_name, "place_name" : review.place.place_name, "rating" : review.rating})

            return redirect('recapp:detail', place_id=place.id)

    else:
        form = ReviewForm()
    #리뷰 등록 이전에 폼을 가져오는 것
    context = {'place': place, 'form': form}
    #place_detail.html에 넘겨줄 인자들 정의, 'place', 'form'
    return render(request, 'recapp/place_detail.html', context)

@login_required(login_url='signapp:signin')
def review_modify(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    if request.user != review.author:
        messages.error(request, '이 리뷰를 수정할 권한이 없습니다.')
        return redirect('recapp:detail', place_id = review.place.id)

    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            review = form.save(commit=False)
            review.author = request.user
            review.modify_date = timezone.now()
            review.save()
            return redirect('recapp:detail', place_id = review.place.id)
        #폼이 invalid 이면 어차피 html에서 form_error를 띄워준다.
    else:
        form = ReviewForm(instance=review)
        #GET이면 그냥 폼 형식만 생성해서 띄워주기
    context = {'review' : review, 'form' : form}
    return render(request, 'recapp/review_form.html', context)
    #review를 수정하기 위한 별도 수정 템플릿으로 보내기

@login_required(login_url='signapp:signin')
def review_delete(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    if request.user != review.author:
        messages.error(request, '이 리뷰를 삭제할 권한이 없습니다.')
    else:
        review.delete()
    return redirect('recapp:detail', place_id = review.place.id)

templates/recapp/place_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ place.place_name }}</h2>
    <div>이 곳과 유사한 맛집들은?</div>
    {% for similar in similars %}
    <div>{{ similar.place_name }}</div>
    {% endfor %}

    {% if place.review_set.count > 0 %}
        <div>평균 평점 : {{ place.average_rating }}</div>
    {% endif %}
    {% if place.review_set.count == 0 %}
        <div>아직 아무도 평가하지 않았습니다.</div>
    {% endif %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ place.place_location }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ place.place_tags }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{place.review_set.count}}개의 리뷰가 있습니다.</h5>
    {% for review in place.review_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-header">{{ review.rating }}점 입니다.</div>
            <div class="card-text" style="white-space: pre-line;">{{ review.content }}</div>
            <div class="d-flex justify-content-end">

                {% if review.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                <div class="mb-2">수정됨</div>
                <div>{{ review.modify_date }}</div>
                </div>
                {% endif %}

                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ review.author.username }}</div>
                    <div>{{ review.create_date }}</div>
                </div>
            </div>

            {% if request.user == review.author %}
        <div class="my-3">
            <!-- 수정과 삭제 -->
            <a href="{% url 'recapp:review_modify' review.id  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary "
               data-uri="{% url 'recapp:review_delete' review.id  %}">삭제</a>
        </div>
        {% endif %}

        </div>
    </div>
    {% endfor %}

<!--리뷰 생성-->
    <form action="{% url 'recapp:review_create' place.id %}" method="post" class="my-3">
        {% csrf_token %}

        {% if form.errors %}
    <div class="alert alert-danger" role="alert">
    {% for field in form %}
        {% if field.errors %}
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
        {% endif %}
    {% endfor %}
    </div>
    {% endif %}

        <div class="form-group">
        <!-- 로그아웃되있는 권한이 없는 anonymous user인 경우 리뷰생성을 disabled 시킨다. -->

            <label for="content">한줄평</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                    name="content" id="content" class="form-control" rows="10"></textarea>
            <label for="rating">평점</label>
            <p><input {% if not user.is_authenticated %}disabled{% endif %}
                    name="rating" id="rating" type="number" min="1" max="5"/><p/>

        </div>
        <input type="submit" value="리뷰등록" class="btn btn-outline-danger">

    </form>
</div>

{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/recapp/place_list.html
{% extends 'base.html' %}
{% block content %}

    {% if recommends %}
        <div>{{ request.user.profile.sofo_name }}님이 좋아할 수도 있는 맛집들</div>
        <div>
        {% for recommend in recommends %}
            <tr>
            <a href="{% url 'recapp:detail' recommend.id %}">{{ recommend.place_name }}</a>
            </tr>
        {% endfor %}
        </div>
    {% endif %}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>맛집</th>
            <th>위치</th>
            <th>#tags</th>
        </tr>
        </thead>
        <tbody>
        {% if place_list %}
        {% for place in place_list %}
        <tr>
            <td>
                <a href="{% url 'recapp:detail' place.id %}">{{ place.place_name }}</a>
                <!-- place 상세 정보 조회를 위해 링크를 걸어 둠 -->
                {% if place.review_set.count > 0 %}
                <span class="text-danger small ml-2">{{ place.review_set.count }}건의 리뷰</span>
                {% endif %}


            </td>
            <td>{{ place.place_location }}</td>
            <td>{{ place.place_tags }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">등록된 맛집이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

<!-- 페이징처리 시작 -->
<!-- 'place_list' 는 page_obj 컨텍스트 임 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if place_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ place_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in place_list.paginator.page_range %}

            {% if page_number >= place_list.number|add:-5 and page_number <= place_list.number|add:5 %}

                {% if page_number == place_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>

                {% endif %}
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if place_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ place_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->

</div>
{% endblock %}

templates/recapp/review_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">한줄평</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
            <label for="rating">평점</label>
            <p><input name="rating" id="rating" type="number"
                      min="1" max="5"/><p/>
        </div>
        <button type="submit" class="btn btn-outline-danger">수정하기</button>
    </form>
</div>

{% endblock %}