django_recsys/urls.py
from django.contrib import admin
from django.urls import path, include
from recapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #관리자 기능을 사용하기 위한 url
    path('', views.index, name='index'),
    #홈으로 이동하기 위한 url
    #현재 사이트의 홈은 recapp의 place_list로 연결되게 설정되어 있으므로, recapp.view의 index가 실행되게 설정
    path('recapp/', include('recapp.urls')),
    #recapp 기능을 사용하기 위한 url => include로 recapp 내부에서 관리
    path('signapp/', include('signapp.urls')),
    #signapp 기능을 사용하기 위한 url => include로 signapp 내부에서 관리
]

recapp/urls.py
from django.urls import path
from . import views

app_name = 'recapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:place_id>/', views.place_detail, name='detail'),
    path('review/create/<int:place_id>/', views.review_create, name='review_create'),
    path('review/create/<int:review_id>', views.review_modify, name='review_modify'),
    path('review/delete/<int:review_id>', views.review_delete, name='review_delete'),
]

signapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
#auth : 로그인/로그아웃 기능이 구현되어 있는 내장 app 즉, 여기서 구현되어 있는 뷰들을 가져온다.


app_name = 'signapp'
#템플릿에서 signapp:path_name 으로 매칭 가능

urlpatterns = [
    path('signin/', auth_views.LoginView.as_view(template_name='signapp/signin.html'), name='signin'),
    #loginview는 디폴트로 registration/login.html 이라는 경로의 템플릿 참조하므로 수정해줌
    path('signout/', auth_views.LogoutView.as_view(), name='signout'),
    path('signup/', views.signup, name='signup'),
    #auth app에서도 회원가입을 지원하는 뷰는 제공하지 않음 => 직접 views에다가 뷰를 작성해야 함
    path('mypage/', views.mypage, name='mypage'),


]

templates/base.html
{% load static %}
<!-- stylesheet를 모듈처럼 import하는 맥락 -->
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <!-- stylesheet를 모듈처럼 import하는 맥락 -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>sofo 맛집 추천</title>
</head>
<body>

<!-- navigation bar -->
{% include 'navbar.html' %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}

{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- 자바스크립트 소스(script) -->
<!-- 부트스트랩은 jquery를 필요로 하므로 jquery 먼저 선언한다. -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->

</body>
</html>

templates/form_errors.html
{% if form.errors %}
    <!-- 로그인 실패 시, 이유를 명시해주기 위해 사용-->
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!--navigation bar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'recapp:index' %}">sofo 맛집 추천</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">

                {% if user.is_authenticated %}
                    <!--로그인 여부에 따라 로그인/아웃 활성화 구분-->
                <a class="nav-link" href="{% url 'signapp:signout' %}">{{ user.username }} (로그아웃)</a>
                    <!-- 프로필 페이지 링크 연결 -->
                    <a class="nav-link" href="{% url 'signapp:mypage' %}">마이 페이지</a>
                {% else %}
                <a class="nav-link" href="{% url 'signapp:signin' %}">로그인</a>
                {% endif %}







            </li>
        </ul>
    </div>
</nav>

templates/sign_form_errors.html
{% if user_form.errors %}
    <!-- 로그인 실패 시, 이유를 명시해주기 위해 사용-->
    {% for field in user_form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in user_form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% if profile_form.errors %}
    <!-- 로그인 실패 시, 이유를 명시해주기 위해 사용-->
    {% for field in profile_form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in profile_form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}