django_recsys/urls.py
from django.contrib import admin
from django.urls import path, include
from recapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #관리자 기능을 사용하기 위한 url
    path('', views.index, name='index'),
    #홈으로 이동하기 위한 url
    #현재 사이트의 홈은 recapp의 place_list로 연결되게 설정되어 있으므로, recapp.view의 index가 실행되게 설정
    path('recapp/', include('recapp.urls')),
    #recapp 기능을 사용하기 위한 url => include로 recapp 내부에서 관리
    path('signapp/', include('signapp.urls')),
    #signapp 기능을 사용하기 위한 url => include로 signapp 내부에서 관리
]

recapp/urls.py
from django.urls import path
from . import views

app_name = 'recapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:place_id>/', views.place_detail, name='detail'),
    path('review/create/<int:place_id>/', views.review_create, name='review_create'),
    path('review/create/<int:review_id>', views.review_modify, name='review_modify'),
    path('review/delete/<int:review_id>', views.review_delete, name='review_delete'),
]

signapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
#auth : 로그인/로그아웃 기능이 구현되어 있는 내장 app 즉, 여기서 구현되어 있는 뷰들을 가져온다.


app_name = 'signapp'
#템플릿에서 signapp:path_name 으로 매칭 가능

urlpatterns = [
    path('signin/', auth_views.LoginView.as_view(template_name='signapp/signin.html'), name='signin'),
    #loginview는 디폴트로 registration/login.html 이라는 경로의 템플릿 참조하므로 수정해줌
    path('signout/', auth_views.LogoutView.as_view(), name='signout'),
    path('signup/', views.signup, name='signup'),
    #auth app에서도 회원가입을 지원하는 뷰는 제공하지 않음 => 직접 views에다가 뷰를 작성해야 함
    path('mypage/', views.mypage, name='mypage'),


]

signapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Avg


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sofo_name = models.CharField(max_length=50, unique=True, verbose_name='sofo 닉네임')

    def __str__(self):
        return self.sofo_name

    @property
    def average_rating(self):
        return round(self.user.review_set.aggregate(Avg('rating'))['rating__avg'], 1)

    class Meta:
        db_table = 'profiles'

signapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

#현재 문제는 장고에서 기본으로 제공되는 회원가입 기능을 쓰는데 이것은 user가 가질 수 있는 속성이 제한되어 있어서
#특수문자를 포함하는 sofo 유저명을 추가할 수 없음 => 새로운 user 객체를 만들 필요가 생김 or Profile 모델을 만들자

#회원가입을 위한 form
class UserForm(UserCreationForm):

    email = forms.EmailField(label="e-mail")
    #sofo_name = forms.CharField(max_length=50, label="sofo_name")

    class Meta:
        model = User
        fields = ('username', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields=('sofo_name',)

signapp/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login
from signapp.forms import UserForm, ProfileForm
from signapp.models import Profile
from django.contrib.auth.decorators import login_required

# Create your views here.

# 회원가입 : 리뷰생성 뷰와 비슷한 맥락임 post인지 get인지를 판단한다.
def signup(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():

            user_form.save()
            profile = profile_form.save(commit=False)

            username = user_form.cleaned_data.get('username')
            raw_password = user_form.cleaned_data.get('password1')

            # credential 매개변수들이 유효하다면, 해당되는 User 객체를 반환해준다.
            user = authenticate(username=username, password=raw_password)
            login(request, user)

            profile.user = user
            # 로그인 전까지는 anonymous user 객체이므로 user 객체를 매핑 할 수 없어서
            # authenticate, login 과정을 거친 후 user 객체가 로그인되면 프로필에 매핑
            profile.save()
            return redirect('index')

    else:
        user_form = UserForm()
        profile_form = ProfileForm()
    return render(request, 'signapp/signup.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

@login_required(login_url='signapp:signin')
def mypage(request):
    user = request.user
    context = {'user' : user}
    return render(request, 'signapp/mypage.html', context)


# def signup(request):
#     if request.method == 'POST':
#         user_form = UserForm(request.POST)
#         profile_form = ProfileForm(request.POST)
#         if user_form.is_valid() and profile_form.is_valid():
#
#             user_form.save()
#             profile = profile_form.save(commit=False)
#
#             username = user_form.cleaned_data.get('username')
#             raw_password = user_form.cleaned_data.get('password1')
#
#             user = authenticate(username=username, password=raw_password)
#             login(request, user)
#
#             profile.user = user
#             # 로그인 전까지는 anonymous user 객체이므로 user 객체를 매핑 할 수 없어서
#             # authenticate, login 과정을 거친 후 user 객체가 로그인되면 프로필에 매핑
#             profile.save()
#
#         else:
#             if profile_form.is_valid() == False:
#                 error_msg = '가입에 실패\n{}'.format(
#                     '\n'.join(
#                         [f'- {error}'
#                          for key, value in profile_form.errors.items()
#                          for error in value]))
#                 return HttpResponse(error_msg)
#                 #return redirect('signapp:signup')
#
#         return redirect('index')
#
#     else:
#         user_form = UserForm()
#         profile_form = ProfileForm()
#     return render(request, 'signapp/signup.html', {
#         'user_form': user_form,
#         'profile_form': profile_form
#     })

templates/signapp/mypage.html
{% extends "base.html" %}

{% block content %}
    <div class="container my-3">
    <h2 class="border-bottom py-2">{{ user.profile.sofo_name }}</h2>
    {% if user.review_set.count > 0 %}
        <div>나의 평균 평점 : {{ user.profile.average_rating }}</div>
    {% else %}
        <div>아직 남긴 리뷰가 없습니다.</div>
    {% endif %}
    </div>
    <h5 class="border-bottom my-3 py-2">{{user.review_set.count}}개의 리뷰를 남겼습니다.</h5>
    {% for review in user.review_set.all %}
    <div class="card my-3">
        <div class="card-body">
           <a href={% url 'recapp:detail' review.place.id %}>{{ review.place.place_name }}</a>
            <div class="card-header">{{ review.rating }}점 입니다.</div>
            <div class="card-text" style="white-space: pre-line;">{{ review.content }}</div>
            <div class="d-flex justify-content-end">

                {% if review.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                <div class="mb-2">수정됨</div>
                <div>{{ review.modify_date }}</div>
                </div>
                {% endif %}

                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ review.author.username }}</div>
                    <div>{{ review.create_date }}</div>
                </div>
            </div>

            {% if request.user == review.author %}
        <div class="my-3">
            <!-- 수정과 삭제 -->
            <a href="{% url 'recapp:review_modify' review.id  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary "
               data-uri="{% url 'recapp:review_delete' review.id  %}">삭제</a>
        </div>
        {% endif %}

        </div>
    </div>
    {% endfor %}
{% endblock %}

templates/signapp/signin.html
{% extends "base.html" %}

{% block content %}
<div class="container my-3">

<div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'signapp:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>

    <form method="post" class="post-form" action="{% url 'signapp:signin' %}">
        {% csrf_token %}

        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL,
         즉, 예를 들어 로그아웃 상태에서 리뷰를 작성할때, 바로 로그인 화면으로 보내지는데, 이후 로그인이 성공하고 나면
         바로 next=로 지정된 리뷰생성 화면으로 보내지게 만들자.-->

        {% include "form_errors.html" %}

        <div class="form-group">
            <!--username, password는 auth app이 필수로 하는 변수. 그냥 건들지 말자-->
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/signapp/signup.html
{% extends "base.html" %}

{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'signapp:signin' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}

        {% include "sign_form_errors.html" %}

        <div class="form-group">
            <label for="username">아이디</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ user_form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="sofo_name">sofo 닉네임</label>
            <input type="text" class="form-control" name="sofo_name" id="sofo_name"
                   value="{{ profile_form.sofo_name.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ user_form.password.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ user_form.password.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ user_form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}